### PR TITLE
Top Nav implemented, CSS cleaned up.

### PR DESCRIPTION
**Pull request by MrRorschach**

### CODE REVIEW

**Comment by sheaACC** [comment]
Screenshot 2024-05-31 at 1 51 24 PM

I'm getting this error when running the site locally.

**Comment by sheaACC** [comment]
I restarted the dev server and am getting the same error. Can you clone the repo into a separate directory, npm install, checkout mega-menu, and npm run dev and see if you get the same thing?

**Comment by MrRorschach** [comment]
This is fixed. The 3 SVGs were added

**Review by sheaACC — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
