### PR TITLE
Reports page styling

### PR DESCRIPTION
**Pull request by MrRorschach**
This is ready to go.

### CODE REVIEW

**Comment by sheaACC** [comment]
@MrRorschach please make the "Search for Tag" box fit inside the main column. 
Screenshot 2024-09-03 at 1 26 00 PM

**Comment by MrRorschach** [comment]
Alright, I have fixed that and made a few other mobile view changes that I missed

**Comment by sheaACC** [comment]
Screenshot 2024-09-05 at 11 35 19 AM

This is my view on mobile. Does it look different on your machine?

**Comment by MrRorschach** [comment]
Yeah mine doesn't have the top menu issue. Have you tried turning your computer on and off again??


But not having it flex on mobile would be ideal so I have made that change now which should fix that issue on your screen

Screenshot 2024-09-05 at 12 41 01 PM

**Comment by MrRorschach** [comment]
This is the new view
Screenshot 2024-09-05 at 12 46 53 PM

**Pull request merged**
