### PR TITLE
About TLED Hero Carousel

### PR DESCRIPTION
**Pull request by MrRorschach**
This should be good to go!

I reused the Carousel component, which required some conditional logic as the homepage carousel is both styled differently and has additional data fields which the normal carousel does not have. 

Also the carousel react component is structured to take the complete JSON object not just the hero section, so that is why I am passing it a different variable compared to 
`layout === 'image'`

### CODE REVIEW

**Comment by sheaACC** [comment]
I rebased from the main branch and now I'm getting this weird error when I run dev. I pushed the rebased branch up. Can you look and see if you can figure out what the problem is?
Screenshot 2024-08-01 at 11 31 01 AM

**Comment by sheaACC** [comment]
I also pushed the latest main branch up and I'm not getting errors there.

**Comment by sheaACC** [comment]
@MrRorschach this might be something weird with Typescript/VS Code. Let me know if you're getting the same error.

**Comment by MrRorschach** [comment]
Ok so this is weird but my homepage folder is not capitalized, but maybe yours is? I get this error instead. '~/components/widgets/Homepage/

I don't know why that would have changed at any point but maybe VSCode changed it automatically for you

Screenshot 2024-08-01 at 12 16 41 PM

**Comment by sheaACC** [comment]
Yeah I think that was a problem with the folder name.

**Pull request merged**
