### PR TITLE
Copyright page styling done

### PR DESCRIPTION
**Pull request by MrRorschach**
- This includes a base level of aesthetics for the templated pages
- Accordion ACF component is done
- Sidebar left component is done
  - Both sidebar components were rearranged so that the order on mobile is correct. They went from flex to flex-row-reverse so the sidebar menu does not appear before the content.

Please let me know if I missed something, I have reviewed the page quite a few times, but sometimes I am so focused on certain elements that I totally miss something major like the accordion not having a title till today.

### CODE REVIEW

**Comment by sheaACC** [comment]
Screenshot 2024-07-30 at 8 47 09 AM
Add padding left and right to the Accordion title so that it has some space in the hover state.

Add indent to the Accordion content.

**Comment by sheaACC** [comment]
Screenshot 2024-07-30 at 8 47 41 AM
Add padding at the bottom of the contact container.

**Comment by MrRorschach** [comment]
Hey, sorry I don't think you have the most recent version.  This is what the accordion looks like on my dev server, I do need to fix that padding at the bottom, so I will do that after my 9AM meeting and push it 

Screenshot 2024-07-30 at 8 56 57 AM

**Comment by sheaACC** [comment]
Sorry, I didn't realize I needed to do a `git pull` with the branch checked out. I thought it I just pulled from the main branch that everything would update downstream. Learning something new everyday.... ;)

**Comment by MrRorschach** [comment]
No worries, I thought if you did a git pull without any other flags it did update all of them, but also who knows what trouble the git gods are causing for their own amusement.

Padding has been added to the one column element

**Review by sheaACC — APPROVED** [review]
Looks good!

**Pull request merged**
